    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Conferam tecum, quam cuique verso rem subicias;",
    "Graece donan, Latine voluptatem vocant.",
    "Quacumque enim ingredimur,",
    "in aliqua historia vestigium ponimus.",
    "Et si turpitudinem fugimus in statu et motu",
    "corporis, quid est cur pulchritudinem non sequamur.",
    "Duo Reges: constructio interrete.",
    "Hoc loco tenere se Triarius non potuit.",
    "Ut proverbia non nulla veriora sint quam vestra dogmata.",
    "Apud imperitos tum illa dicta sunt,",
    "aliquid etiam coronae datum.",
    "Traditur, inquit, ab Epicuro ratio neglegendi doloris.",
    "Quid de Platone aut de Democrito loquar.",
    "Te enim iudicem aequum puto, modo quae dicat ille bene noris.",
    "Mihi quidem Antiochum, quem audis, satis belle videris attendere.",
    "Ergo hoc quidem apparet, nos ad agendum esse natos.",
    "Quae diligentissime contra Aristonem dicuntur a Chryippo.",
    "Nec vero alia sunt quaerenda contra Carneadeam illam sententiam.",
    "Quid est igitur, cur ita semper deum",
    "appellet Epicurus beatum et aeternum.",
    "Neque enim civitas in seditione beata esse",
    "potest nec in discordia dominorum domus.",
    "Si longus, levis.",
    "Sic enim censent, oportunitatis esse beate vivere.",
    "Indicant pueri, in quibus ut in speculis natura cernitur.",
    "Sin kakan malitiam dixisses, ad aliud nos unum",
    "certum vitium consuetudo Latina traduceret.",
    "Sed haec nihil sane ad rem.",
    "Eorum enim est haec querela, qui",
    "sibi cari sunt seseque diligunt.",
    "Virtutis, magnitudinis animi, patientiae,",
    "fortitudinis fomentis dolor mitigari solet.",
    "Et hunc idem dico, inquieta sed ad",
    "virtutes et ad vitia nihil interesse.",
    "Aliter enim explicari, quod quaeritur, non potest.",
    "Non quaeritur autem quid naturae tuae",
    "consentaneum sit, sed quid disciplinae.",
    "Nam illud vehementer repugnat, eundem",
    "beatum esse et multis malis oppressum.",
    "Piso, familiaris noster, et alia multa et",
    "hoc loco Stoicos irridebat: Quid enim.",
    "Omnes enim iucundum motum, quo sensus hilaretur.",
    "Multoque hoc melius nos veriusque quam Stoici.",
    "Quid loquor de nobis, qui ad laudem et ad",
    "decus nati, suscepti, instituti sumus.",
    "Vitiosum est enim in dividendo partem in genere numerare.",
    "Quae sequuntur igitur.",
    "Nam si propter voluptatem, quae est",
    "ista laus, quae possit e macello peti.",
    "Profectus in exilium Tubulus statim nec respondere ausus.",
    "Scio enim esse quosdam, qui quavis",
    "lingua philosophari possint.",
    "Ita ne hoc quidem modo paria peccata sunt.",
    "Nondum autem explanatum satis, erat,",
    "quid maxime natura vellet.",
